[output]
feature-depth = 1

[licenses]
version = 2
allow = [
    #"0BSD",
  "Apache-2.0",
  "Apache-2.0 WITH LLVM-exception",
  "BSD-2-Clause",
    #"BSD-3-Clause",
  "BSL-1.0",
   "CC0-1.0",
    #"ISC",
  "MIT",
    #"MIT-0",
    #"Unlicense",
    #"Zlib",
]

exceptions = [
  { name = "unicode-ident", allow = [
    "Unicode-DFS-2016",
    "Unicode-3.0",
  ] },
]
# The confidence threshold for detecting a license from license text.
confidence-threshold = 0.9
[bans]
multiple-versions = "deny"
wildcards = "deny"
allow-wildcard-paths = true
highlight = "all"

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = []

